version: '3.8'

services:
  telegram-bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    user: "1000:1000"  # Use a specific user ID to maintain consistent permissions
